# ============================================
# API Gateway - Docker Compose 환경
# ============================================

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://portal-universe:30000/auth-service
          jwk-set-uri: http://portal-universe:30000/auth-service/oauth2/jwks

# Docker 환경 디버깅용 상세 로그
logging:
  level:
    root: INFO