# ============================================
# API Gateway - Kubernetes 환경
# ============================================

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://portal-universe:8080/auth-service
          jwk-set-uri: http://api-gateway:8080/auth-service/oauth2/jwks

# 운영 환경 로그
logging:
  level:
    root: INFO
