# ============================================
# API Gateway 공통 설정 (라우팅 규칙)
# ============================================

server:
  netty:
    connection-timeout: 2s

spring:
  cloud:
    gateway:
      # 전역 필터
      default-filters:
        - name: PreserveHostHeader

      # X-Forwarded 헤더 처리
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true

      # Discovery 설정
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      # 라우팅 규칙
      routes:
        # ========== Auth Service ==========
        # ========== POST /login ==========
        - id: auth-service-login-post-handler
          uri: lb://auth-service
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RewritePath=/login, /auth-service/login
            - name: PreserveHostHeader
          order: 0

        # ========== 정적 리소스 처리 ==========
        - id: auth-service-static-resources
          uri: lb://auth-service
          predicates:
            - Path=/default-ui.css,/favicon.ico,/webjars/**
          filters:
            - RewritePath=/(.*), /auth-service/$1
            - name: PreserveHostHeader
          order: 0

        # ========== OAuth2/OIDC 프로토콜 ==========
        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/oauth2/**,/auth-service/.well-known/**,/auth-service/connect/**
          filters:
            - StripPrefix=1
            - name: PreserveHostHeader
          order: 1

        # ========== 로그인/로그아웃 페이지 ==========
        - id: auth-service-security-pages
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/login,/auth-service/logout
            - Method=GET
          filters:
            - StripPrefix=1
            - name: PreserveHostHeader
          order: 2

        # ========== Auth Service REST API ==========
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2  # /api/auth 제거
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
          order: 3

        # ========== Blog Service ==========
        - id: blog-service-route
          uri: lb://blog-service
          predicates:
            - Path=/api/blog/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: blogCircuitBreaker
                fallbackUri: forward:/fallback/blog

        # ========== Shopping Service ==========
        - id: shopping-service-route
          uri: lb://shopping-service
          predicates:
            - Path=/api/shopping/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: shoppingCircuitBreaker
                fallbackUri: forward:/fallback/shopping

# Resilience4j Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

    instances:
      authCircuitBreaker:
        base-config: default
      blogCircuitBreaker:
        base-config: default
      shoppingCircuitBreaker:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      authCircuitBreaker:
        base-config: default
      blogCircuitBreaker:
        base-config: default
      shoppingCircuitBreaker:
        base-config: default