# ============================================
# API Gateway 공통 설정 (라우팅 규칙)
# ============================================

server:
  netty:
    connection-timeout: 2s

spring:
  cloud:
    gateway:
      # 전역 필터
      default-filters:
        - name: PreserveHostHeader

      # X-Forwarded 헤더 처리
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true

      # Discovery 설정
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      # 라우팅 규칙
      routes:
        # ========== Auth Service ==========
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: auth-service-internal
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: PreserveHostHeader

        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/login,/logout,/oauth2/**,/assets/**
          filters:
            - name: PreserveHostHeader

        # ========== Blog Service ==========
        - id: blog-service-route
          uri: lb://blog-service
          predicates:
            - Path=/api/blog/**
          filters:
            - name: CircuitBreaker
              args:
                name: blogCircuitBreaker
                fallbackUri: forward:/fallback/blog

        # ========== Shopping Service ==========
        - id: shopping-service-route
          uri: lb://shopping-service
          predicates:
            - Path=/api/shopping/**
          filters:
            - name: CircuitBreaker
              args:
                name: shoppingCircuitBreaker
                fallbackUri: forward:/fallback/shopping

# Resilience4j Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

    instances:
      authCircuitBreaker:
        base-config: default
      blogCircuitBreaker:
        base-config: default
      shoppingCircuitBreaker:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      authCircuitBreaker:
        base-config: default
      blogCircuitBreaker:
        base-config: default
      shoppingCircuitBreaker:
        base-config: default
