# ============================================
# API Gateway 공통 설정 (라우팅 규칙)
# ============================================

server:
  netty:
    connection-timeout: 2s

spring:
  cloud:
    gateway:
      # 전역 필터
      default-filters:
        - name: PreserveHostHeader

      # X-Forwarded 헤더 처리
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true

      # Discovery 설정
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      # 라우팅 규칙
      routes:
        # ========== Auth Service ==========
        # 1. OAuth2/OIDC 프로토콜 엔드포인트
        - id: auth-service-protocol
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/oauth2/**,/auth-service/.well-known/**,/auth-service/connect/**
          filters:
            - StripPrefix=1
            - name: PreserveHostHeader
          order: 1

        # 2. 로그인/로그아웃 페이지 (HTML)
        - id: auth-service-pages
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/login,/auth-service/logout
          filters:
            - StripPrefix=1
            - name: PreserveHostHeader
          order: 2

        # 3. 정적 리소스 (CSS, JS 등)
        - id: auth-service-assets
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/assets/**,/auth-service/resources/**
          filters:
            - StripPrefix=1
          order: 3

        # 4. Auth Service REST API
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/api/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
          order: 4

        # 5. 기타 Auth Service 내부 경로 (최하위)
        - id: auth-service-default
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
          order: 5

        # ========== Blog Service ==========
        - id: blog-service-route
          uri: lb://blog-service
          predicates:
            - Path=/api/blog/**
          filters:
            - name: CircuitBreaker
              args:
                name: blogCircuitBreaker
                fallbackUri: forward:/fallback/blog

        # ========== Shopping Service ==========
        - id: shopping-service-route
          uri: lb://shopping-service
          predicates:
            - Path=/api/shopping/**
          filters:
            - name: CircuitBreaker
              args:
                name: shoppingCircuitBreaker
                fallbackUri: forward:/fallback/shopping

# Resilience4j Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

    instances:
      authCircuitBreaker:
        base-config: default
      blogCircuitBreaker:
        base-config: default
      shoppingCircuitBreaker:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      authCircuitBreaker:
        base-config: default
      blogCircuitBreaker:
        base-config: default
      shoppingCircuitBreaker:
        base-config: default
