spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth-service
          jwk-set-uri: http://localhost:8080/auth-service/oauth2/jwks
logging:
  level:
    root: INFO