# ============================================
# API Gateway - Docker Compose 환경
# ============================================

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api-gateway:8080/auth-service
          jwk-set-uri: http://auth-service:8081/oauth2/jwks

# Docker 환경 디버깅용 상세 로그
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.security: DEBUG
