# ============================================
# API Gateway - Kubernetes 환경
# ============================================

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://portal-universe:8080/auth-service
          jwk-set-uri: http://auth-service:8081/oauth2/jwks

# 운영 환경 로그
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.portal.universe.apigateway: DEBUG
