# ============================================
# 모든 서비스, 모든 환경에 적용되는 기본값
# ============================================

spring:
  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Kafka Producer 공통 Serializer
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

# 분산 추적용 로그 포맷 (모든 환경 동일)
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
