# ============================================
# Auth Service - Kubernetes 환경
# ============================================
server:
  forward-headers-strategy: framework
  use-forward-headers: true
  servlet:
    session:
      timeout: 1h

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:laze}
    password: ${DB_PASSWORD:password} # TODO: Kubernetes Secret에서 주입
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  security:
    oauth2:
      # OAuth2 Client 설정 (더미 값 - 소셜 로그인 비활성화 상태)
      client:
        registration:
          google:
            client-id: disabled-in-kubernetes
            client-secret: disabled-in-kubernetes
      # Authorization Server 설정
      authorizationserver:
        issuer: http://portal-universe:30000/auth-service
        client:
          portal-client:
            redirect-uris:
              - http://portal-universe:30000/callback
              - http://portal-universe:30000/silent-renew.html
            post-logout-redirect-uris:
              - http://portal-universe:30000

# 운영 환경 로그 레벨 (INFO)
logging:
  level:
    org.springframework.security: INFO
