# ============================================
# Auth Service - 로컬 개발 환경
# ============================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:laze}
    password: ${DB_PASSWORD:password}
  
  jpa:
    show-sql: true  # 로컬에서는 SQL 출력
    hibernate:
      ddl-auto: update
  
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080/auth-service

# Gateway 기본 URL 설정
gateway:
  base-url: http://localhost:8080

# OAuth2 클라이언트 커스텀 설정
oauth2:
  client:
    redirect-uris: http://localhost:30000/callback
    post-logout-redirect-uris: http://localhost:30000

# 로컬 디버깅용 상세 로그
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG