# ============================================
# Auth Service - Kubernetes 환경
# ============================================

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:laze}
    password: ${DB_PASSWORD:password} # TODO: Kubernetes Secret에서 주입
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  security:
    oauth2:
      authorizationserver:
        issuer: http://portal-universe:8080/auth-service
        client:
          portal-client:
            redirect-uris:
              - http://localhost:30000/callback
              - http://portal-universe:8080/callback
            post-logout-redirect-uris:
              - http://localhost:30000
              - http://portal-universe:8080

# 운영 환경 로그 레벨 (INFO)
logging:
  level:
    org.springframework.security: INFO