# ============================================
# Auth Service - Docker Compose 환경
# ============================================

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:laze}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: update
  
  security:
    oauth2:
      authorizationserver:
        issuer: http://api-gateway:8080/auth-service
        client:
          portal-client:
            redirect-uris:
              - http://localhost:30000/callback
            post-logout-redirect-uris:
              - http://localhost:30000

# Docker 환경 디버깅용 상세 로그
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE
    org.springframework.security.oauth2.server.authorization: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG