spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: laze
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080/auth-service
      client:
        redirect-uris: http://localhost:30000/callback
        post-logout-redirect-uris: http://localhost:30000

logging:
  level:
    root: INFO
