# ============================================
# Auth Service - 로컬 개발 환경
# ============================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:laze}
    password: ${DB_PASSWORD:password}
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080/auth-service
        settings:
          login-page-url: http://localhost:8080/auth-service/login

# OAuth2 클라이언트 환경별 설정 (커스텀 경로)
oauth2:
  client:
    redirect-uris: http://localhost:30000/callback
    post-logout-redirect-uris: http://localhost:30000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.context.config: DEBUG