spring:
  data:
    mongodb:
      uri: mongodb://laze:password@mongodb:27017/blog_db?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://portal-universe:30000/auth-service
          jwk-set-uri: http://auth-service:8081/oauth2/jwks
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location: ${java.io.tmpdir}

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  metrics:
    tags:
      application: ${spring.application.name}

aws:
  s3:
    access-key: test
    secret-key: test
    bucket-name: blog-bucket
    region: ap-northeast-2
    endpoint: http://localstack:4566