spring:
  data:
    mongodb:
      uri: mongodb://laze:password@localhost:27017/blog_db?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth-service
