spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/shopping_db?useSSL=false&allowPublicKeyRetrieval=true
    username: laze
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://portal-universe:30000/auth-service
          jwk-set-uri: http://auth-service:8081/oauth2/jwks

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  metrics:
    tags:
      application: ${spring.application.name}