spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopping_db?useSSL=false&allowPublicKeyRetrieval=true
    username: laze
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
